all : histogramme

histogramme:
	g++ -Wall -I ../librairie -o bin/histogramme src/histogramme.cpp
expansion:
	g++ -Wall -I ../librairie -o bin/expansion src/expansion.cpp
clean : 
	rm -rf obj/*.o
mrproper :
	rm -rf bin/*
