all : test_grey

test_grey:
	g++ -Wall -I ../librairie -o bin/test_grey src/test_grey.cpp
test_grey2 :
	g++ -Wall -I ../librairie -o bin/test_grey2 src/test_grey2.cpp
clean : 
	rm -rf obj/*.o
mrproper :
	rm -rf bin/*
